### ISSUE TITLE
on_gettext have a massive footprint

### ISSUE THREAD

**Issue by jonathan-dejong** [bonny/WordPress-Simple-History#432] opened 2024-03-06 13:48 UTC
**Describe the bug**

On going through some client sites with the code profiler pro plugin (https://code-profiler.com/) we have found that at least one of the filters on `gettext` in the plugin have a very large footprint on a sites performance.
The cause is this line:
`add_filter( 'gettext', array( $this, 'on_gettext' ), 10, 3 );`
in the file: `loggers/class-plugin-logger.php`

I can't really understand why this particular one have such an impact since it has an early escape based on the `$pagenow`. 
But I can clearly see the impact using the code profile plugin.

**To Reproduce**
1. Install Code Profiler plugin
2. Run profile on any frontend page
3. Review profile data
4. See tab "Methods and functions performance". 

**Expected behavior**

I expect Simple History to have basically 0% impact on frontend loads.

**Screenshots**

![Screenshot 2024-03-06 at 14 46 59](https://github.com/bonny/WordPress-Simple-History/assets/1508751/c0781eee-f3bc-4460-9a85-cd993cf5f216)

**System information (please complete the following information):**
- WordPress version: 6.3
- PHP version: 7.4
- Installed plugins: Not relevant

**Comment by bonny** [comment] 2024-03-07 07:37
Thanks for the report. Can you see in your logs/profile info how many times the function has been called? The gettext filter can be called many many times so maybe that's why it shows up, even if the code exits early there will be a looot of early exists.

**Comment by jonathan-dejong** [comment] 2024-03-12 09:23
I don't have that at the moment but yes we can safely assume it is run MANY times given how gettext works :) 
The thing that strikes me as weird is that this particular hooked function is the one that is reported as really affecting performance, even though there's ~4 hooks on gettext in this plugin alone 🤔

**Comment by bonny** [comment] 2024-03-17 10:35
Did some quick testing with xdebug and it's called "many" times but my understanding of what xdebug shows is that it does not consume that much cpu. We can probably make it better by moving the logic out from each gettext-call so we only add the filter on the page where it's used. But in my tests it does not use as much cpu as your screenshot implies. 

Do you have any other plugins installed on that site?

The sample was taken on a default install on the default frontpage with theme Twenty Twenty-Four.

![CleanShot 2024-03-17 at 11 30 08@2x](https://github.com/bonny/WordPress-Simple-History/assets/221570/823149e7-1fcf-4d98-abab-ce780f4dacec)

![CleanShot 2024-03-17 at 11 31 14@2x](https://github.com/bonny/WordPress-Simple-History/assets/221570/1cc64fd2-16a5-4acc-a4fe-f3c5a4c09661)

**Comment by bonny** [comment] 2024-05-04 18:53
Closing as I can't reproduce it.

**Closed by bonny** 2024-05-04 18:53 UTC
Labels: performance
