### ISSUE TITLE
get PHP Warning at ACF logger

### ISSUE THREAD

**Issue by RicherYang** [bonny/WordPress-Simple-History#252] opened 2021-05-19 10:12 UTC
After update to PHP 8
When update post get the Warning message

`Warning:  reset(): Argument #1 ($array) must be passed by reference, value given in \wp-content\plugins\simple-history\loggers\Plugin_ACF.php on line 529`

**Comment by bonny** [comment] 2022-10-31 07:47
Maybe related/similar:
https://wordpress.org/support/topic/strpos-error-2/

> PHP Warning: strpos() expects parameter 1 to be string, array given in /wp-content/plugins/simple-history/loggers/Plugin_ACF.php on line 482, referer: /wp-admin/post.php?post=123&action=edit

> ```
> if ( strpos( $val, 'field_' ) === 0 ) {
>	continue;
> }```

**Comment by bonny** [comment] 2023-06-25 18:37
Unable to reproduce this so closing. Please open a new issue if error still occurs.

**Closed by bonny** 2023-06-25 18:37 UTC
Labels: bug, PHP8, ACF logger
