### ISSUE TITLE
Post update performance issue

### ISSUE THREAD

**Issue by zacscott** [bonny/WordPress-Simple-History#270] opened 2021-11-23 02:13 UTC
**Describe the bug**

We are seeing large performance degradation when saving a post. You can see in the screenshot below it is taking approximately 7 seconds to update the Simple History tables.

Is there any to improve the performance of these logging calls? Ideally without reducing the retention period.

**To Reproduce**

We have a retention period of 60 days currently (plugin default). There is approximately 1 million records in the wp_simple_history_contexts table.

To reproduce:

1. Edit an existing post.
2. Make an update to the post content (Gutenberg editor).
3. Save the post and inspect the REST API call response time.

**Expected behavior**

Ideally we wouldn't be seeing any major spikes in response time. Something under 1-2 seconds would be sensible.

**Screenshots**

Here is an example of the slow response times from a REST call. We are using New Relic for this performance profiling:

**System information (please complete the following information):**
 - WordPress version: 5.8.2
 - PHP version: 7.4
 - Simple History verison: 2.42.0 (will test with latest ASAP).
 - Installed plugins:
+-----------------------------------------+----------+-----------+--------------+
| name                                    | status   | update    | version      |
+-----------------------------------------+----------+-----------+--------------+
| acf-quickedit-fields                    | active   | none      | 3.1.6        |
| admin-columns-pro                       | active   | available | 5.5.3        |
| adminimize                              | active   | none      | 1.11.7       |
| advanced-custom-fields-pro              | active   | available | 5.10.2       |
| aioseo-news-sitemap                     | active   | available | 1.0.4-beta   |
| aioseo-redirects                        | active   | available | 1.1.2-beta   |
| all-in-one-seo-pack-pro                 | active   | available | 4.1.4.3-beta |
| co-authors-plus                         | active   | available | 3.4.91       |
| query-monitor                           | active   | none      | 3.7.1        |
| simple-history                          | active   | available | 2.42.0       |
| simple-page-ordering                    | active   | none      | 2.3.4        |
+-----------------------------------------+----------+-----------+--------------+

**Comment by bonny** [comment] 2021-11-24 15:08
Hi! Did you have any screenshots? I don't think they are included in the issue.

**Comment by bonny** [comment] 2023-06-29 09:33
Can't reproduce this so closing. Please open a new issue if the issue still persist.

**Closed by bonny** 2023-06-29 09:33 UTC
