### ISSUE TITLE
Simple-History plugin seems to disturb the plugin "Booked" resetting password procedure (plugin hangs).

### ISSUE THREAD

**Issue by HatthaBasel** [bonny/WordPress-Simple-History#253] opened 2021-05-25 10:50 UTC
Hi,

on our website www.hattha-thaispa.ch/reservation users can register to make appointments for a massage. If an already registered user has lost his password, he can reset it by clicking on the link "I forget my password". Afterwards the user has to enter his eMail-address and click on the button "RESET PASSWORD". After clicking on this button the spinning watch turns endlessly with its message "Please wait ..." (see attached screenshot).

When I deactivate the Simple-History plugin, this procedure work smoothly with no problems and the user gets an eMail with a link to reset his password.

This issue is reproducible at any time.

1. go to our [reservation page](www.hattha-thaispa.ch/reservation) and select a day and click on the button "BOOK APPOINTMENT" in a time slot
2. In the form "Request an Appointment" click on "Current customer" and then click on the link "I forget my password". Then enter the eMail-address sukuma.pavises@gmail.com  .
3. After a click on the button "RESET PASSWORD" you will see the spinning watch turns endlessly with its message "Please wait ...".

I would be very happy, if you would be interessed in solving this issue. Any feedback is appreciated.

Best regards

Markus Rubeli

website plugin "Booked": https://getbooked.io/

![Screenshot booked reset password spinning watch in loop](https://user-images.githubusercontent.com/84774962/119483572-663bd880-bd55-11eb-99e9-a3bd5aab095f.jpg)
![Screenshot booked reset password issue](https://user-images.githubusercontent.com/84774962/119483603-6fc54080-bd55-11eb-9858-c7d02085dafc.jpg)

**Comment by bonny** [comment] 2021-05-25 19:25
Thanks for the bug report @HatthaBasel. Can you provide some more info about your server, for example PHP-version and what other plugins you have installed?

**Comment by HatthaBasel** [comment] 2021-05-25 22:18
Dear Pär

in the attachment you will find your desired information. With the plugin
"Plugin Detective - Troubleshooting" we could analyze that Simple-History
Plugin seems to be the culprit.

Kind regards

Markus
www.hattha-thaispa.ch/reservation



*Hattha Thai Massage*
*Mittlere Strasse 69*
*Entrance corner Friedensgasse*
*4056 Basel*

*Mobile: 079 393 90 06*

*eMail:   ***@***.*** ***@***.***>*


Am Di., 25. Mai 2021 um 21:25 Uhr schrieb Pär Thernström <
***@***.***>:

**Comment by bonny** [comment] 2021-05-26 11:07
Thanks for the update. I can not try https://getbooked.io/ because it costs money so unfortunately I don't think I can debug this issue any further.

**Comment by HatthaBasel** [comment] 2021-05-26 11:16
Hi Pär

When we give you access to our backend with admin rights you should be able
to debug right?

Best regards

Markus
www.hattha-thaispa.ch/reservation



*Hattha Thai Massage*
*Mittlere Strasse 69*
*Entrance corner Friedensgasse*
*4056 Basel*

*Mobile: 079 393 90 06*

*eMail:   ***@***.*** ***@***.***>*


Am Mi., 26. Mai 2021 um 13:08 Uhr schrieb Pär Thernström <
***@***.***>:

**Comment by HatthaBasel** [comment] 2021-06-03 18:19
Dear Pär

we urgently need your support to solve this issue. To solve this issue
timely is very importent  for our customers and us. We are willing to give
you our credentials to login to the backend, so you can debug the plugins.
Please help.

Best regards

Markus
www.hattha-thaispa.ch/reservation



*Hattha Thai Massage*
*Mittlere Strasse 69*
*Entrance corner Friedensgasse*
*4056 Basel*

*Mobile: 079 393 90 06*

*eMail:   ***@***.*** ***@***.***>*


Am Mi., 26. Mai 2021 um 13:08 Uhr schrieb Pär Thernström <
***@***.***>:

**Comment by bonny** [comment] 2021-06-03 19:57
@HatthaBasel I need to be able to debug this locally on my computer. What license is the booking plugin, perhaps you are allowed to give a copy of it? You could also try to contact the author of the plugin and see if they can give away a licence for debugging this issue.

**Comment by HatthaBasel** [comment] 2021-06-03 21:08
Dear Pär

The "Booked" plugin was included in the "PEARL"- Theme.

Kind regards

Markus
www.hattha-thaispa.ch/reservation



*Hattha Thai Massage*
*Mittlere Strasse 69*
*Entrance corner Friedensgasse*
*4056 Basel*

*Mobile: 079 393 90 06*

*eMail:   ***@***.*** ***@***.***>*


Am Do., 3. Juni 2021 um 22:03 Uhr schrieb Pär Thernström <
***@***.***>:

**Comment by bonny** [comment] 2021-06-05 07:49
Thanks for the update, however the Pearl theme also seems to cost money, so without the plugin or the theme that contains the plugin, I can not debug this.

**Comment by bonny** [comment] 2021-07-20 19:08
Can't find a way to reproduce this, so closing.

**Closed by bonny** 2021-07-20 19:08 UTC
Labels: Needs investigation
