### ISSUE TITLE
Simple History Has Faulty Data! Extreme Error.

### ISSUE THREAD

**Issue by dec-mail** [bonny/WordPress-Simple-History#466] opened 2024-10-02 06:31 UTC
**Describe the bug**
Earlier, i had some premonitions of possible data faults.

Today, i had VERY clear example.

The data history showed NO activity for a developer for TWO DAYS - yet i had separate records, wheni double checked, saying he had logged in twice over that period!!!

This is an extremely serious error.
What if i had sacked him for not working for two days??????

As per the matra i used to teach in the past - 'Bad data is (much) worse than no data.'
![fts-sajjad-loging-02-10-2024 13-11-16](https://github.com/user-attachments/assets/cd4dad16-a83a-409f-b310-d3c037275862)
![fts-sajjad-logins-02-10-2024 13-11-16](https://github.com/user-attachments/assets/18f725e5-2588-4a2f-b4b1-47b93c752d98)

**Screenshots**
See attached

**System information (please complete the following information):**
- WordPress version: [e.g. 5.8]
- PHP version: [e.g. 7.2]
- Installed plugins: [e.g. Akismet, JetPack, ...]

**Comment by dec-mail** [comment] 2024-10-02 06:38
UPDATE.

This data eventually came up - i mean about 5 min later.
So there is a possible issue of SITE performamce.

**Comment by bonny** [comment] 2024-10-02 07:59
Thanks for the bug report. I can't reproduce this and has so far not experienced it on any site. Are you able to reproduce it somehow?

If the data came up but after a short while maybe it's because of some server cache configuration or some issue with another plugin installed on your site. If you can provide some more info about your server setup and what wp version, db version, and what plugins you have installed, it may give some clues about why this happens for you.

**Comment by jessekafor** [comment] 2024-10-02 13:34
I had an issue where I was not able to see a login attempt from a bad IP and I use an apache server with varnish cache.

**Comment by bonny** [comment] 2024-10-02 15:00
> I had an issue where I was not able to see a login attempt from a bad IP and I use an apache server with varnish cache.

The IP would not affect what's being logged. Maybe some other security related software or plugin stopped to attempt before it reached WordPress? It's difficult to say how/why this happens without more information.

**Comment by bonny** [comment] 2024-10-03 14:59
I'm closing this since the info did show up for original poster. If you encounter this again in a reproducible way please post again.

**Closed by bonny** 2024-10-03 14:59 UTC
